### ISSUE TITLE
The interpretation of Receipt Number seems not correct.

### ISSUE THREAD

**Issue by douglaslear** [vicdus/uscis-case-statistics#17]
The interpretation of Receipt Number seems not correct. 
Take MSC219108XXXX as an example.
If 21 means the year, and 910 means the working day number, we have a problem: we don't have 910 working days in one year.
In the example, the "9" after "21" seems to be a special label. It can be 7, 8, or 9. Most people have it as 9.
The "108" after "9" is the working day number. This number can be as large as 100+ or 200+, as we do have that many days in one year.
The last 4 digits, instead of 5 digits, represent the USCIS Case Number (of a particular day).

Refer to an article here: https://www.moonbbs.com/forum.php?mod=viewthread&action=printable&tid=2824677.

**Comment by vicdus** [comment]
will update this in next deploy
