### ISSUE TITLE
Looks like USCIS has changed the request format from GET to POST

### ISSUE THREAD

**Issue by dabirdweius** [vicdus/uscis-case-statistics#36]
https://github.com/vicdus/uscis-case-statistics/blob/6c664b8ac3db042345217ededbcdbf7f2882c1f0/src/scraper/main.go#L176

My crawler also failed today. Looks like USCIS has change the request format from GET to POST.

**Comment by vicdus** [comment]
fix wip

**Comment by vicdus** [comment]
fixed https://github.com/vicdus/uscis-case-statistics/commit/01412826a2dd9b7a9ae2dae4db661a1549f2623f
